// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"StandardProject/gozero/book/service/user/cmd/rpc/internal/user"
	"context"

	"StandardProject/gozero/book/service/user/cmd/rpc/internal/logic"
	"StandardProject/gozero/book/service/user/cmd/rpc/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IdReq) (*user.UserInfoReply, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
